### DISCUSSION TITLE
One socket-proxy per container or one for all?

### DISCUSSION THREAD

**Discussion by 123mariachi123** [11notes/docker-socket-proxy#3] [Q&A] [answered]
Hi, i am wondering whats the best way to use the socket proxy. I have two docker services running that require access to the socket-proxy. Currently i connect both to one socket-proxy that i run in a separete compose file. 
I have port 2375 open and connect the other two containers with 

``` yml
environment:
      DOCKER_HOST: tcp://socket-proxy:2375
networks:
      - socket-proxy-net
...
```

Now i am wondering if its better to have one socket-proxy per compose.yml since it would allow me to take advantage of the health check and depends_on.

How do you use it?
