### ISSUE TITLE
Proxy error 502 bad gateway

### ISSUE THREAD

**Issue by 123mariachi123** [11notes/docker-socket-proxy#2]
First of all, thanks for this nice project. It looks really interesting but i have problems getting it to work.
I guess i am doing something wrong here so it would be great if @11notes or someone else could point out the problem.

Here is my yml. Btw i tried the same with exposing port 2375/tcp and adding DOCKER_HOST: tcp://socket-proxy:2375 to the watchtower environment. But that leads to the same problem.
I am doing basically the same with another socket-proxy and it works. 

The error i am getting is
```
watchtower                  | time="2025-03-24T21:17:06+01:00" level=error msg="request returned 502 Bad Gateway for API route and version http://%2Fvar%2Frun%2Fdocker.sock/v1.44/containers/json?filters=%7B%22status%22%3A%7B%22created%22%3Atrue%2C%22exited%22%3Atrue%2C%22restarting%22%3Atrue%2C%22running%22%3Atrue%7D%7D, check if the server supports the requested API version"
```
and
```
watchtower2-socket-proxy-1  | 2025/03/24 20:17:08 http: proxy error: dial unix /run/docker.sock: connect: permission denied
```

Thanks for suggestens!

``` yml
services:
  socket-proxy:
    container_name: socket-proxy
    image: 11notes/socket-proxy:2.0.0
    volumes:
      - /run/docker.sock:/run/docker.sock:ro  # Mount the host Docker socket
      - socket-proxy:/run/proxy  # This is where the proxy socket will be created
    restart: always

  watchtower:
    container_name: watchtower
    image: beatkind/watchtower:amd64-latest
    restart: always
    volumes:
      - socket-proxy:/var/run
    #  - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_REMOVE_VOLUMES: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_LOG_LEVEL: info
      TZ: Europe/Berlin
      
volumes:
  socket-proxy:
```
