### ISSUE TITLE
proxy error: use of closed network connection

### ISSUE THREAD

**Issue by 123mariachi123** [11notes/docker-socket-proxy#4]
Hi @11notes, sorry that i keep coming back with questions 😄 

I tried to switch to the latest image 2.1.1 now but i get this error. With 2.1.0 i don't see it

```
socket-proxy-1 has been recreated
socket-proxy-1  | 2025/03/31 07:44:32 starting ...
socket-proxy-1  | 2025/03/31 07:44:32 starting proxy UNIX socket ...
socket-proxy-1  | 2025/03/31 07:44:32 starting proxy TCP socket ...
socket-proxy-1  | 2025/03/31 07:44:32 proxy connection to docker socket established
socket-proxy-1  | 2025/03/31 07:44:37 blocked: HEAD /_ping
dozzle          | {"level":"info","version":"v8.12.0","time":"2025-03-31T07:44:37Z","message":"Dozzle agent version v8.12.0"}
dozzle          | {"level":"info","version":"v8.12.0","time":"2025-03-31T07:44:37Z","message":"Agent listening on [::]:7007"}
socket-proxy-1  | 2025/03/31 07:44:47 http: proxy error: context canceled
socket-proxy-1  | 2025/03/31 07:44:47 httputil: ReverseProxy read error during body copy: read unix @->/run/docker.sock: use of closed network connection
dozzle          | {"level":"error","version":"v8.12.0","error":"unexpected EOF","host":"dozzle-ext","time":"2025-03-31T07:44:47Z","message":"docker store unexpectedly disconnected from docker events"}
dozzle          | {"level":"error","version":"v8.12.0","error":"request returned 502 Bad Gateway for API route and version http://%2Fvar%2Frun%2Fdocker.sock/v1.48/events, check if the server supports the requested API version","host":"dozzle-ext","time":"2025-03-31T07:44:52Z","message":"docker store unexpectedly disconnected from docker events"}
socket-proxy-1  | 2025/03/31 07:44:52 http: proxy error: read unix @->/run/docker.sock: use of closed network connection
socket-proxy-1  | 2025/03/31 07:44:52 http: proxy error: read unix @->/run/docker.sock: use of closed network connection
dozzle          | {"level":"error","version":"v8.12.0","error":"request returned 502 Bad Gateway for API route and version http://%2Fvar%2Frun%2Fdocker.sock/v1.48/events, check if the server supports the requested API version","host":"dozzle-ext","time":"2025-03-31T07:44:57Z","message":"docker store unexpectedly disconnected from docker events"}
socket-proxy-1  | 2025/03/31 07:44:57 http: proxy error: read unix @->/run/docker.sock: use of closed network connection
```

the compose yml for my dozzle service:

```yml
services:
  socket-proxy:
    image: 11notes/socket-proxy:2.1.1
    restart: unless-stopped
    user: 0:996
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - socket-proxy:/run/proxy
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    depends_on:
      socket-proxy:
        condition: service_healthy
        restart: true
    command: agent
    environment:
      DOZZLE_HOSTNAME: dozzle-immich
      DOZZLE_LEVEL: info
    ports:
      - 7007:7007
    volumes:
      - socket-proxy:/var/run
volumes:
  socket-proxy: null
networks: {}
```

Any idea what causes this problem?

And a second question, you also see the line
`socket-proxy-1  | 2025/03/31 07:44:37 blocked: HEAD /_ping`
in the logs above. I do see the same message in 2.1.0. Is this something to be concerned about? Is something blocking access to the docker socket? 

Thanks for your help!
